openapi: 3.0.0
info:
  title: 03-Jobs-API
  version: 1.0.0
servers:
  - url: https://foad-jobs-api.onrender.com/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Auth
  - name: Jobs
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: john
                email: john43@gmail.com
                password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: john33@gmail.com
                password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /jobs/:
    get:
      tags:
        - Jobs
      summary: Get Jobs
      security:
        - bearerAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmY2NzU2M2I2MmVlYTE2YmM1ZjNlNTAiLCJpYXQiOjE3Mjc0Mjc5MzksImV4cCI6MTcyNzUxNDMzOX0.a0jauknvxP7e4uMmvTcL6CJ9H97jS-B-GrWcC8QR6OI
        - name: Cache-Control
          in: header
          schema:
            type: string
          example: no-cache
        - name: Postman-Token
          in: header
          schema:
            type: string
          example: <calculated when request is sent>
        - name: Host
          in: header
          schema:
            type: string
          example: <calculated when request is sent>
        - name: User-Agent
          in: header
          schema:
            type: string
          example: PostmanRuntime/7.39.1
        - name: Accept
          in: header
          schema:
            type: string
          example: "*/*"
        - name: Accept-Encoding
          in: header
          schema:
            type: string
          example: gzip, deflate, br
        - name: Connection
          in: header
          schema:
            type: string
          example: keep-alive
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Jobs
      summary: Create Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: SOFIP
                position: solutionneur
                status: en attente
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
    get:
      tags:
        - Jobs
      summary: Get Single Job
      security:
        - bearerAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmY2NzU2M2I2MmVlYTE2YmM1ZjNlNTAiLCJpYXQiOjE3Mjc0Mjc5MzksImV4cCI6MTcyNzUxNDMzOX0.a0jauknvxP7e4uMmvTcL6CJ9H97jS-B-GrWcC8QR6OI
        - name: Cache-Control
          in: header
          schema:
            type: string
          example: no-cache
        - name: Postman-Token
          in: header
          schema:
            type: string
          example: <calculated when request is sent>
        - name: Host
          in: header
          schema:
            type: string
          example: <calculated when request is sent>
        - name: User-Agent
          in: header
          schema:
            type: string
          example: PostmanRuntime/7.39.1
        - name: Accept
          in: header
          schema:
            type: string
          example: "*/*"
        - name: Accept-Encoding
          in: header
          schema:
            type: string
          example: gzip, deflate, br
        - name: Connection
          in: header
          schema:
            type: string
          example: keep-alive
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Jobs
      summary: Update Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: en attente
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Jobs
      summary: Delete Job
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
